### ISSUE TITLE
Neclaritati revisal online

### ISSUE THREAD

**Issue by LeonteOana** [reges-ro/integrare#10]
1. In cazul in care o firma doreste sa isi tina Revisalul in softul de salarii cum se va exporta baza de date din Revisal Online pentru a fi utilizata la import. Din vechiul revisal, cu conectare la baza de date DB, aveam posibilitatea de a importa tot istoricul de salariati.
2. Din prezentarea online am inteles ca prin API se vor face doar operatiuni de Adaugare/modifcare date fara operatii de citire. In cazul in care un angajator modifica datele unui contract in interfata web cum se va face sincronizarea cu informatiile existente in baza de date.
Exemplu: Prin API am trasnmis o incetare de suspendare cu o anumita data, dar, clientul o modifica din interfata web. 
3. Cum preluam referintele contractelor existente pentru importul in bazele de date?

**Comment by cornelA2007** [comment]
> 1. In cazul in care o firma doreste sa isi tina Revisalul in softul de salarii cum se va exporta baza de date din Revisal Online pentru a fi utilizata la import. Din vechiul revisal, cu conectare la baza de date DB, aveam posibilitatea de a importa tot istoricul de salariati.
> 2. Din prezentarea online am inteles ca prin API se vor face doar operatiuni de Adaugare/modifcare date fara operatii de citire. In cazul in care un angajator modifica datele unui contract in interfata web cum se va face sincronizarea cu informatiile existente in baza de date.
>    Exemplu: Prin API am trasnmis o incetare de suspendare cu o anumita data, dar, clientul o modifica din interfata web.
> 3. Cum preluam referintele contractelor existente pentru importul in bazele de date?

@LeonteOana Cum reusiti sa va conectati la baza de date DB pentru a importa tot istoricul fiecarui salariat?

**Comment by bogdannedelcu** [comment]
> 1. In cazul in care o firma doreste sa isi tina Revisalul in softul de salarii cum se va exporta baza de date din Revisal Online pentru a fi utilizata la import. Din vechiul revisal, cu conectare la baza de date DB, aveam posibilitatea de a importa tot istoricul de salariati.
> 2. Din prezentarea online am inteles ca prin API se vor face doar operatiuni de Adaugare/modifcare date fara operatii de citire. In cazul in care un angajator modifica datele unui contract in interfata web cum se va face sincronizarea cu informatiile existente in baza de date.
>    Exemplu: Prin API am trasnmis o incetare de suspendare cu o anumita data, dar, clientul o modifica din interfata web.
> 3. Cum preluam referintele contractelor existente pentru importul in bazele de date?

Va fi o optiune de export baza de date disponibila in aplicatia web, accesibila doar dupa ce reprezentatul legal s-a autentificat cu identitate digitala.

**Comment by bogdannedelcu** [comment]
> > 1. In cazul in care o firma doreste sa isi tina Revisalul in softul de salarii cum se va exporta baza de date din Revisal Online pentru a fi utilizata la import. Din vechiul revisal, cu conectare la baza de date DB, aveam posibilitatea de a importa tot istoricul de salariati.
> > 2. Din prezentarea online am inteles ca prin API se vor face doar operatiuni de Adaugare/modifcare date fara operatii de citire. In cazul in care un angajator modifica datele unui contract in interfata web cum se va face sincronizarea cu informatiile existente in baza de date.
> >    Exemplu: Prin API am trasnmis o incetare de suspendare cu o anumita data, dar, clientul o modifica din interfata web.
> > 3. Cum preluam referintele contractelor existente pentru importul in bazele de date?
> 
> @LeonteOana Cum reusiti sa va conectati la baza de date DB pentru a importa tot istoricul fiecarui salariat?

@CornelAnghel baza de date Revisal este in format SQLite si o gasiti in Windows intr-un folder specific userului logat pe statie. 

C:\Documents and Settings\nume_utilizator\AppData\Roaming\TeamNet\Revisal sau
sau c:\Users\Nume_Utilizator\AppData\Roaming\Teamnet\Revisal\  depinde de sistemul de operare

**Comment by veemex** [comment]
> > 1. In cazul in care o firma doreste sa isi tina Revisalul in softul de salarii cum se va exporta baza de date din Revisal Online pentru a fi utilizata la import. Din vechiul revisal, cu conectare la baza de date DB, aveam posibilitatea de a importa tot istoricul de salariati.
> > 2. Din prezentarea online am inteles ca prin API se vor face doar operatiuni de Adaugare/modifcare date fara operatii de citire. In cazul in care un angajator modifica datele unui contract in interfata web cum se va face sincronizarea cu informatiile existente in baza de date.
> >    Exemplu: Prin API am trasnmis o incetare de suspendare cu o anumita data, dar, clientul o modifica din interfata web.
> > 3. Cum preluam referintele contractelor existente pentru importul in bazele de date?
> 
> Va fi o optiune de export baza de date disponibila in aplicatia web, accesibila doar dupa ce reprezentatul legal s-a autentificat cu identitate digitala.

In ce perioada va fi accesibila aceasta functionalitate si sub ce forma/structura se vor elibera informatiile? Vom obtine o baza de date cu aceeasi structura ca actualul Revisal.db sau va fi ceva diferit ?

**Comment by CornelAnghel** [comment]
@bogdannedelcu # Ma gandesc ca trebuie gasita o solutie care sa poata sincroniza baza de date din softul de salarii cu informatiile introduse direct in interfata web (daca se vor introduce informatii atat in softul de salarii cat si direct pe interfata web).

**Comment by BogdanCiocaltea** [comment]
> Oricand se vor putea exporta referintele contractelor din interfata web, nu anticipez o limitare pe o perioada de timp. Structura va fi XML sau JSON si va cuprinde informati

Structura propusa va fi foarte limitata si nu cred ca va permite ca XML-ul sa contina intreg istoricul salariatului, cel putin daca seamana cu formatul XML vechi (care era un snapshot al starii curente - fara istoric) din care se transforma pana acum in fisierul rvs. Va rog sa va ganditi la o posibilitate de a pune la dispozitie un API de tip GET prin care sa interogam istoricul complet al unui salariat sau chiar istoricul complet al unui angajator (toti salariatii). Este foarte necesar importului initial de date in cazul implementarilor de software HR nou pentru o companie, pana acum reuseam sa extragem din Revisal.db. Va rog sa oferiti o solutie simpla si pentru Revisal Online de extragere a datelor, XML-ul este din punctul meu de vedere o solutie defectuoasa.
