### ISSUE TITLE
Blocker/Nu se mai poate adauga un salariat-eroare

### ISSUE THREAD

**Issue by TestareRev** [reges-ro/integrare#108]
![image](https://github.com/user-attachments/assets/cbf3c7e1-19d3-4c65-b8fa-31e6fd2ea90c)
![image](https://github.com/user-attachments/assets/11ccedb3-14fb-42df-ab79-99d771ee57e8)

**Comment by bogdannedelcu** [comment]
a fost o problema temporara, daca mai intampinati va rog sa ne comunicati
