### ISSUE TITLE
Raportare contract nou - timp raspuns

### ISSUE THREAD

**Issue by CornelAnghel** [reges-ro/integrare#11]
Cum se procedeaza prin API pentru un salariat nou intr-o firma? Se transmite intai salariatul si se asteapta returnarea MesajuluiResult pentru a prelua “codsalariat”, apoi se face o noua transmitere pentru a trimite contractul identificat prin codsalariat primit anterior urmand a se primi MesajResult cu “Codcontract”? Sau se face o singura transmitere si salariat si contract?
Daca se face in 2 etape: care e timpul de raspuns in care primim MesajResult ce contine “codsalariat” pentru a-l prelua ca referinta la transmitere contract nou? (tinand cont de termenele legale de raportare contract nou)

**Comment by bogdannedelcu** [comment]
> Cum se procedeaza prin API pentru un salariat nou intr-o firma? Se transmite intai salariatul si se asteapta returnarea MesajuluiResult pentru a prelua “codsalariat”, apoi se face o noua transmitere pentru a trimite contractul identificat prin codsalariat primit anterior urmand a se primi MesajResult cu “Codcontract”? Sau se face o singura transmitere si salariat si contract? Daca se face in 2 etape: care e timpul de raspuns in care primim MesajResult ce contine “codsalariat” pentru a-l prelua ca referinta la transmitere contract nou? (tinand cont de termenele legale de raportare contract nou)

Se face in 2 etape cum ati descris mai sus. 
Raspunsul la operatia de adaugare salariat va fi prioritizat astfel incat sa primiti codul de salariat in termen foarte scurt de ordinul secundelor.

**Comment by bogdannedelcu** [comment]
@oliverxy Sa genereze softurile terte GUID de sallariat nu e recomandat pentru ca pot genera dubluri. 
Analizam daca putem sa primim simultan atat Contractul cat si Salariatul doar pentru cazul primei depuneri. O consecinta ar fi ca o eventuala eroare de introducere a salariatului ar anula si contractul. In plus ar trebui ca sistemul sa va raspunda cu ambele GUID-uri, de Salariat si Contract nou adaugat. Cautam o solutie si revenim

**Comment by BogdanCiocaltea** [comment]
O particularitate a tipului de date GUID este ca este imposibil de generat de 2 ori aceeasi valoare, deci este exclus ca 2 sisteme terte externe diferite, pentru salariati/contracte diferite, sa "propuna" acelasi GUID (decat daca il copiaza si nu il genereaza nou). Deci da, o metoda sa salvati voi cu GUID de la sistemul extern, este o varianta. De asemenea puteti voi sa faceti o verificare ca nu mai exista cu acelasi GUID deja. Ar fi utila ca prima depunere sa permita salariat + contract, si este normal sa anuleze contractul daca are eroare salariatul. Asa s-ar fi intamplat si daca se transmitea succesiv, corectai salariatul apoi si retrimiteai.

**Comment by bogdannedelcu** [comment]
Retinem ca data transmisiei salariatului va fi un element afisat in registrul salariatului alaturi de data transmisiei contractului, iar eventualele probleme tehnice ale Reges-Online care au generat o intarziere se vor consemna pentru o corecta interprertare ale acestor date.

**Comment by bogdannedelcu** [comment]
> O particularitate a tipului de date GUID este ca este imposibil de generat de 2 ori aceeasi valoare, deci este exclus ca 2 sisteme terte externe diferite, pentru salariati/contracte diferite, sa "propuna" acelasi GUID (decat daca il copiaza si nu il genereaza nou). Deci da, o metoda sa salvati voi cu GUID de la sistemul extern, este o varianta. De asemenea puteti voi sa faceti o verificare ca nu mai exista cu acelasi GUID deja. Ar fi utila ca prima depunere sa permita salariat + contract, si este normal sa anuleze contractul daca are eroare salariatul. Asa s-ar fi intamplat si daca se transmitea succesiv, corectai salariatul apoi si retrimiteai.

Riscul dublarii la care ma refer este sa introduca de 2 ori acelasi salariat, cu acelasi CNP dar GUID-uri diferit.
