### ISSUE TITLE
Corecți Reges

### ISSUE THREAD

**Issue by TDG0508** [reges-ro/integrare#13]
Buna ziua, 
As dori sa adresez și eu o întrebare legată de modificarea / corectarea /anularea suspendărilor deja încetate având in vedere ca noi le vom opera/corecta pentru a fi in sistemul nostru de Hr(SAP), care va fi modalitatea de sincronizare între SAP și API /Web Reges precum si apariția in baza de date unica pana la momentul in care exista disponibilitatea unei funcții de corecție. Luand in calcul faptul ca noi deja facem aceste modificări in aplicația noastră locala(SAP). Prin urmare, care va fi modalitatea de actualizare a bazei de date unice inclusiv istoricul angajaților și noile anulări sau modificări . Mulțumesc,

**Comment by bogdannedelcu** [comment]
@TDG0508 avem in analiza aceasta posibilitate de a modifica elemente transmise in trecut atat prin aplicatia web cat si prin API. Modalitatea va fi prin intermediul mesajelor din schema XSD publicata, ce analizam este daca sa permitem si care ar fi precondițiile pentru o astfel de modificare in trecut.
