### ISSUE TITLE
Mediu test API

### ISSUE THREAD

**Issue by LeonteOana** [reges-ro/integrare#14]
Buna ziua, 

Cand veti publica mediul de test API? 
Initial s-a spus ca pe data de 15 septembrie, apoi s-a amanat pe 30 sepembrie. La data actuala nu este nimic disponibil pentru testare. 
Multumesc!

**Comment by bogdannedelcu** [comment]
Am pus aici detaliile https://github.com/reges-ro/integrare/issues/19
