### ISSUE TITLE
Optiune de blocare a operarii in aplicatia web

### ISSUE THREAD

**Issue by CiprianPetrea** [reges-ro/integrare#16]
In momentul in care se activeaza pentru un angajator un cont de utilizator API pentru o aplicatie, atunci aceasta ar trebui sa fie singura cale de adaugare/modificare date. In acest sens, ar fi utila o optiune de blocare a operarii in Web. 
Sugestia mea ar fi chiar de a desemna o aplicatie unica cu drepturi de adaugare/modificare date. In caz contrar, in lipsa unor endpoint-uri de citire, va deveni aproape imposibil de sincronizat baza de date proprie cu cea online.

**Comment by nagualul** [comment]
Cred ca nu e ok sa fie blocat Web-ul. 
Ce faci daca-ti pica calculatorul iar reparatia lui dureaza X zile... ?

**Comment by CiprianPetrea** [comment]
Cred ca in cazul unei avarii pe sistemul propriu, ar trebui sa dai temporar controlul aplicatiei web. Dupa remediere, ar trebui sa blochezi iar operarea in web, sa operezi manual modificarile in sistemul propriu, marcandu-le cu id-urile din aplicatia web (ar trebui sa fie vizibile pe undeva) pentru a nu le mai transmite prin API.

**Comment by bogdannedelcu** [comment]
Notam sugestia si venim cu o propunere
