### ISSUE TITLE
Interogari Multiple

### ISSUE THREAD

**Issue by ICristiI** [reges-ro/integrare#2]
Datele aferente transmise in sistem de catre angajatori vor fi disponibile pentru interogari pe criterii multiple/ date de intrare multiple la nivel de IM/ITM ?
Exemplu interogari... CNP multiplu catti barbati cate femei / medie salar...etc
CUI multiplu  cate pe CAEN 1 ...2  media salarului pe caen etc

**Comment by bogdannedelcu** [comment]
> Datele aferente transmise in sistem de catre angajatori vor fi disponibile pentru interogari pe criterii multiple/ date de intrare multiple la nivel de IM/ITM ? Exemplu interogari... CNP multiplu catti barbati cate femei / medie salar...etc CUI multiplu cate pe CAEN 1 ...2 media salarului pe caen etc

nu inteleg la ce va referiti, puteti da un exemplu concret? 
Daca e vorba de ce anume se poate interoga in backoffice nu pot sa va raspund, pot doar sa clarific ce anume se va putea interoga in nou aplicatie de angajator
