### ISSUE TITLE
Lista salariati, lista contracte nu aduce date

### ISSUE THREAD

**Issue by LeonteOana** [reges-ro/integrare#20]
![lista goala](https://github.com/user-attachments/assets/741f5ba2-3a6a-46ee-bbbc-329d62cbaf49)

**Comment by bogdannedelcu** [comment]
Inca nu merge cautarea cu Nume, pana atunci puteti folosi primele cifre din CNP

**Comment by LeonteOana** [comment]
Am incercat. 
![image](https://github.com/user-attachments/assets/69003431-c3c8-40c8-ad08-01c4f597b775)

**Comment by bogdannedelcu** [comment]
Mai verificati odata va rog?

În vin., 25 oct. 2024 la 08:12 Oana Leonte ***@***.***> a
scris:

**Comment by LeonteOana** [comment]
Acum functioneaza.
