### ISSUE TITLE
MessageId, SessionId

### ISSUE THREAD

**Issue by LeonteOana** [reges-ro/integrare#21]
Ce reprezinta MessageId, SessionId?

**Comment by bogdannedelcu** [comment]
MessageID este un identificator unic al mesajului transmis completat de emitator, presupunem ca va fi generat unic la transmiterea mesajului. Poate fi identificatorul cu care il salvati in baza voastra de date.

SessionID este rezervat, se va completa cu 00000000-0000-0000-0000-000000000000 sau orice alt identificator pana cand vom modifica schema.
