### ISSUE TITLE
Selectie elemente din lista

### ISSUE THREAD

**Issue by CornelAnghel** [reges-ro/integrare#23]
1. Ar mai trebui imbunatatita lista de selectie COR la adaugare contract adica sa se poate face o filtrare partiala dupa anumite cuvinte/caractere; la fel si la temeiuri suspendare si unde mai apar liste derulante (nomenclatoare cu mai mult de 6-7 elemente in lista) sa  poate fi redusa lista pe masura ce sunt scrise caractere de la tastatura care se regasesc in elementele din lista integrala.
2. Operatia incetare suspendare in aplicatie nu pare sa fie finalizata (dezvoltata); apare mesaj Tip contract*summary not found*

**Comment by bogdannedelcu** [comment]
![image](https://github.com/user-attachments/assets/14255341-60c4-49b0-919f-32fa58d671b4)

Pentru claritate, e vorba de a putea scrie text si a filtra elmentele din dropdown?

Momentan se poate doar daca se da click in zona editabila

**Comment by CornelAnghel** [comment]
DA, am reusit acum. Initial se deschidea o fereastra cu lista si nu puteam tasta in casuta.
