### ISSUE TITLE
Status SUCCES dar description de failed 

### ISSUE THREAD

**Issue by panaitsilviu** [reges-ro/integrare#24]
La angajare se primeste Result code SUCCES dar din descriere reiese contrariul Salariatul SAMPATH SUMEDHA cu CNP 123987456 nu a putut fi adăugat!

 <MessageResult>
        <Header xmlns="http://www.inspectiamuncii.ro/reges2025">
            <MessageId>117f9b03-9efb-4f5e-8ebb-7ab3b0c792af</MessageId>
            <ClientApplication>SAP</ClientApplication>
            <Version>5</Version>
            <Operation>InregistrareSalariat</Operation>
            <AuthorId>2f96bffc-5547-4093-a8cc-99c207171d5d</AuthorId>
            <SessionId>117f9b04-9efb-4f5e-8ebb-7ab3b0c792cf</SessionId>
            <User>Ion</User>
            <Timestamp>2024-10-15T08:41:00.9338387+00:00</Timestamp>
        </Header>
        <ResponseId xmlns="http://www.inspectiamuncii.ro/reges2025">39e008fd-2fc9-4234-afc8-1da3e41b3a1a</ResponseId>
        <Result xmlns="http://www.inspectiamuncii.ro/reges2025">
            <Code>SUCCES</Code>
            <Description>Salariatul SAMPATH SUMEDHA cu CNP 123987456 nu a putut fi adăugat!</Description>
            <Ref>3ce46ea0-aed4-49ca-a60e-706a6c14a4f8</Ref>
        </Result>
    </MessageResult>

**Comment by bogdannedelcu** [comment]
am publicat un fix la API, va rog incercati din nou

**Comment by panaitsilviu** [comment]
Este ok, multumesc.
