### ISSUE TITLE
GET: Salariat, Contract - nu functioneaza

### ISSUE THREAD

**Issue by LeonteOana** [reges-ro/integrare#25]
404 Not Found
Requested resource could not be found. 😐

**Comment by bogdannedelcu** [comment]
Nu avem in plan sa expunem prin API astfel de cereri. Au ramas cumva prin exemple?

**Comment by LeonteOana** [comment]
![image](https://github.com/user-attachments/assets/7dfa046d-ed4c-44e9-80a4-cab3926ea41a)

**Comment by bogdannedelcu** [comment]
Multumesc pentru info, le vom sterge din exemplul postman
