### ISSUE TITLE
Preluare registru HG500 - 2011

### ISSUE THREAD

**Issue by LeonteOana** [reges-ro/integrare#28]
Functioneaza pagina Preluare registru HG500 - 2011 ? 
Daca se preiau salariatii din Revisal pentru un CUI valid exista implicatii in aplicatia Revisal?

**Comment by bogdannedelcu** [comment]
Functionalitatea de "Preluare registru HG500" este in lucru, revenim cu detalii cand va fi operationalizata.

**Comment by LeonteOana** [comment]
> Functionalitatea de "Preluare registru HG500" este in lucru, revenim cu detalii cand va fi operationalizata.

Aveti un termen estimativ privind finalizarea acesti functionalitati?

**Comment by LeonteOana** [comment]
Acest tichet inca mai este de actualitate!
