### ISSUE TITLE
Mutare/Transfer contract

### ISSUE THREAD

**Issue by BogdanCiocaltea** [reges-ro/integrare#29]
Cum se adauga un contract preluat prin transfer intre societati? In specificatiile API si in exemplele Postman nu am regasit aceasta situatie: sa fac AdaugareContract pentru un contract preluat prin transfer pe societatea pentru care raportez, de la alta societate (mutare angajator in cazul achizitiilor / fuziunilor). Il adaug simplu si apoi fac alta operatie cu detaliile de transfer si cum? Daca exista documentatie si exemple si mie mi-au scapat, va rog sa ma ajutati cu detalii.

**Comment by bogdannedelcu** [comment]
Inca nu e clarificat mecanismul de Transfer/Detasare.

O sa incerc un rezumat: A si B, A transfera catre B, planul este ca A sa trimita o operatie de Transfer/Detasare, in Reges se va marca acel contract ca "Propus spre transfer/detasare" iar B va descarca baza a celor primiti, o va importa in propriul sistem si va emite un mesaj de ReceptieTransfer pe UUID-urile contracelor respective.

Revenim cu explicatii mai clare pentru aceste doua spete.
