### ISSUE TITLE
Corectie/Anulare suspendari

### ISSUE THREAD

**Issue by GeorgyanaB** [reges-ro/integrare#3]
Va exista posibilitatea de a modifica perioada sau chiar de a anula o suspendare deja incetata? In prezent nu exista aceasta posibilitate, si in practica sunt situatii cand sunt necesare. De ex.: a solicitat concediu fara plata si ulterior aduce un concediu medical care se suprapune total/partial cu concediul fara plata si il aduce dupa incetarea concediului fara plata.

**Comment by bogdannedelcu** [comment]
> Va exista posibilitatea de a modifica perioada sau chiar de a anula o suspendare deja incetata? In prezent nu exista aceasta posibilitate, si in practica sunt situatii cand sunt necesare. De ex.: a solicitat concediu fara plata si ulterior aduce un concediu medical care se suprapune total/partial cu concediul fara plata si il aduce dupa incetarea concediului fara plata.

Luam in considerare o posibilitate de corectie a erorilor materiale sau de alta natura datorita acestor tipuri de evenimente care se intalnesc in practica
