### ISSUE TITLE
Cerere access sistem extern / Chei API nu imi merge

### ISSUE THREAD

**Issue by csmisi** [reges-ro/integrare#30]
Buna ziua

Ca dezvoltator de software tot incerc sa generez access la sistemul de teste pe adresa data insa nu merge generarea API Keys. Am incercat sa adaug si o a doua CUI sa vad insa nici accessul la CUI-ul secundar nu mi-a dat. Efectiv la "Cerere access sistem extern" imi spune mesajul "Am transmis informațiile necesare generării credențialelor." insa nu imi arata cheia si parola. Gresesc eu undeva? Am urmarit pasii din prezentarea din 15 octombrie. 

Si o intrebare, scuzati-ma daca nu aici trebuie sa scriu insa nu am gasit la cine trebuie sa transmit mesaj direct pe WhatsApp: ca dezvoltator de software unde trebuie sa ma inscriu sa primesc invitatie la sedintele din viitor?

Multumesc

**Comment by bogdannedelcu** [comment]
Buna ziua @csmisi ,  va rog puneti o poza cu ercanul de unde incercati sa obtineti cheia si eventual mesajul de eroare

Aici este link de conectare la grup https://chat.whatsapp.com/K13isQatMerIqwFIbnIMI2

**Comment by bogdannedelcu** [comment]
Aplicatia a fost actualizata in zona meniului, acum asa arata 
![image](https://github.com/user-attachments/assets/ad864747-699a-49db-a25d-fb1245bd7a63)

**Comment by csmisi** [comment]
Eu am lucrat pe baza prezentarii din 15 octombrie. Cer cheia API:
![Capture1Test](https://github.com/user-attachments/assets/f04b2615-f907-4b2d-a3e8-7a78b8e8bd0e)

si imi raspunde insa nu primesc raspunsul cu user si parola, numai mesajul 

![Capture2Test](https://github.com/user-attachments/assets/7a5bb82d-ab33-4063-b411-296b4c3052bc)

La fel si cu cerere access

**Comment by bogdannedelcu** [comment]
am verificat, revenim cu vesti

**Comment by bogdannedelcu** [comment]
Am remediat @csmisi puteti verifica va rog?

**Comment by csmisi** [comment]
Da, totul este okay, merge, Mersi frumos, de maine fac teste
