### ISSUE TITLE
listare api toti salariatii

### ISSUE THREAD

**Issue by ooo4321** [reges-ro/integrare#31]
cum se pot lista toti salariatii ?
in postman s-a oferit exemplu pentru a obtine punctual pentru un salariat metodat get 
{{URL}}/api/Salariat/CB83FC73-08F8-4312-8C45-D44FE8B61881

Dar cum se poate obtine lista completa de salariati inregistrati si id-urile acestora, am incercat fara id si nu obtin un raspuns ?

**Comment by bogdannedelcu** [comment]
Buna ziua @ooo4321, listarea salariatilor nu este oferita prin API, vom furniza un export al bazei de date din aplicatia Web pe care il veti putea folosi la initializarea sistemelor terte.

Prin API puteti transmite informatii din bazele de date cu privire la Salariati si Contracte. In mesajele de raspuns de tip MessageResult primite cand apelati PoolMessage sau ReadMessage veti degasi ID-ul salariatului/contractului adaugat.
