### ISSUE TITLE
notificari modidificari

### ISSUE THREAD

**Issue by nagualul** [reges-ro/integrare#32]
Bună ziua,

Mă gândesc că ar fi util un sistem de notificare, la care să ne putem abona, pentru modificări asupra aplicației (schema XSD, funcționalități API, etc) astfel încât, dezvoltatorii de softuri să afle rapid de ele, fără să-și facă un alt task zilnic de "scormonit" cine știe prin câte zeci de pagini web / pdf / alte surse.
Probabil ar fi suficient chiar și un fișier text, pus aici pe git, de versionare...

Mulțumesc.

**Comment by bogdannedelcu** [comment]
@nagualul multumim pentru sugestie, vom publica un Release Notes in curand.

pana atunci va recomand sa va abonati la orice modificare din acest reporitory, nu sunt foarte dese asa ca nu genereaza spam

![image](https://github.com/user-attachments/assets/05f44bc3-7590-421f-a296-adf9dba6ec17)

**Comment by CornelAnghel** [comment]
Cum pot seta ca toate notificarile sa le primesc (inclusiv cele noi), nu doar cele la care m-am abonat?
