### ISSUE TITLE
Modificare | Corectie sporuri contract > MessageResponse >ResponseId

### ISSUE THREAD

**Issue by soimbogdan** [reges-ro/integrare#35]
Salutare,

In JSON-ul de actiune modificare/corectie contract exista proprietatea "referintaSpor" in array-ul [Contract > Continut > sporuriSalariu] . Am reusit sa inregistrez mai multe actiuni de modificare/corectii contract activ dar API-ul a facut tot timpul operatiiune de ADD pentry sporurile contractului. Pentru a putea actualiza ('AddOrUpdate' / 'Delete') avem nevoie separat de acel primaryKey ?
Am inteles principiul MessageResponse > ResponseId pentru inregistrare salariat/contract dar cum procedam pentru actualizare sporuri contract ? Astept feedback-ul vostru.

Bogdan,

bogdan@robite.ro

O zi buna

**Comment by soimbogdan** [comment]
Buna ziua,

Nu inteleg care GET atata timp cat nu exista metode de GET in API ?
Puteti sa imi exemplificati printr-un exemplu concret cum se face Get la SporResponseID ? 
In urma unei actiuni de InregistrareContract primim un ID care este alocat contractului, nu unui spor anume din contractul trimis in reges.

Multumesc,

**Comment by cmandragiu** [comment]
Au fost actualizate componentele sistemului astfel încât acum există posibilitatea de a transmite sporuri cu **_referințe generate de client_** (referința este de tip Guid).

La exemplul de adăugare contract cu sporuri din proiectul POSTMAN puteți acum adăuga fiecărui spor elementul ReferintaSpor cu o referință generată.

Pentru modificarea contractelor:
- Sporurile cu referințe care nu se regăsesc în registru vor fi adăugate.
- Sporurile cu referințe care se regăsesc în registru vor rămâne nemodificate în registru (în continuare nu se vor putea modifica sporurile existente).
- Sporurile adăugate anterior și care nu mai sunt transmise prin apeluri de modificare contract vor fi eliminate din registru.

Pentru a modifica un spor se vor transmite datele modificate ale acelui spor însă cu o nouă referință.

**Comment by soimbogdan** [comment]
Buna,

Am testat dar nu imi apar datele corect in interfata web. 
Atasat toate fisierele.
![Screenshot 2024-10-31 122119](https://github.com/user-attachments/assets/6e3b8bc4-a859-4b17-adbc-c152e23cdfed)

[adaugareContract_a3f2edf3-d675-46f9-b08c-a0508f2489fb.json](https://github.com/user-attachments/files/17586357/adaugareContract_a3f2edf3-d675-46f9-b08c-a0508f2489fb.json)
[modificareContract_32ba1bd3-0cbf-42d5-a5a1-cd0a9aaa7694.json](https://github.com/user-attachments/files/17586358/modificareContract_32ba1bd3-0cbf-42d5-a5a1-cd0a9aaa7694.json)

**Comment by soimbogdan** [comment]
O scurta completare..pe linia cu angajarea 'Data la care produce efecte' este 31.10.2024 ( vedeti json trimis) iar pe WEB apare 01.11.2024

**Comment by soimbogdan** [comment]
Buna ziua,

Am reluat azi pasii pe un contract nou si au functinat toate operatiile.
