### ISSUE TITLE
Obtinere ID salariat/contract

### ISSUE THREAD

**Issue by Stihii** [reges-ro/integrare#38]
Pentru salariatii importati de pe vechiul Revisal cum se va putea obtine ID-ul unui salariat respectiv al unui contract in vederea inregistrarii unor noi operatiuni sau modificari?

In general exista posibilitatea de a obtine ID-urile acestea prin vreo metoda in caz ca se intampina vreo eroare in stocarea ID-ului primit in urma crearii salariatului/contractului prin API?

**Comment by bogdannedelcu** [comment]
Din aplicatia Web se va putea exporta lista de contracte/salariati in format XML/JSON

**Comment by Stihii** [comment]
Si in ea se vor regasi ID-urile?

**Comment by bogdannedelcu** [comment]
da
