### ISSUE TITLE
Prezentare Reges-Online - 5 Iulie 2024

### ISSUE THREAD

**Issue by bogdannedelcu** [reges-ro/integrare#4]
Gasiti aici prezentarea Powerpoint si inregistrarea video a sedintei din data de 5 Iulie 2024

https://drive.google.com/drive/folders/12clzkH9VgShmcjxQlZJTAAp4EPsKfuxu?usp=sharing.

**Comment by andreea-moisa** [comment]
Buna ziua,
Ati putea sa imi spuneti care va fi modul de functionare al Noului Revisal?
- bazele locale actuale de revisal se vor migra in Noul revisal?
- vor mai exista instalari/baze de date locale de revisal?
- modificarile (nou angajati, Acte Aditionale, Suspendari, Reveniri din Suspendare, Incetari) indiferent daca vin prin import dintr-o aplicatie de HR sau vor fi operate manual se vor scrie intr-o baza de date unica? 
In sensul ca daca utilizatorul opteaza pentru operarea manuala sau pentru export xml/rvs dintr-o aplicatie de HR si import in revisal toate aceste modificari se scrie intr-o baza de date unica iar reprezentantul angajatorului are acces la istoricul unui salariat indiferent de sursa unde au fost operate modificarile ce tin de activitatea de administrare de personal?
Multumesc,

**Comment by bogdannedelcu** [comment]
> Buna ziua,
> 
> Ati putea sa imi spuneti care va fi modul de functionare al Noului Revisal?
> 
> - bazele locale actuale de revisal se vor migra in Noul revisal?

Sa va migra baza centrala, veti regasi in noua aplicatie Angajator disponibila online datele incarcate pana la momentul trecerii la noul sistem.

> 
> - vor mai exista instalari/baze de date locale de revisal?

Nu vor mai exista baze locale pentru cei care folosesc aplicatia Angajator. Cei care folosesc API probabil vor mentine o baza locala.

> 
> - modificarile (nou angajati, Acte Aditionale, Suspendari, Reveniri din Suspendare, Incetari) indiferent daca vin prin import dintr-o aplicatie de HR sau vor fi operate manual se vor scrie intr-o baza de date unica? 

Intelegerea este corecta.

> 
> In sensul ca daca utilizatorul opteaza pentru operarea manuala sau pentru export xml/rvs dintr-o aplicatie de HR si import in revisal toate aceste modificari se scrie intr-o baza de date unica iar reprezentantul angajatorului are acces la istoricul unui salariat indiferent de sursa unde au fost operate modificarile ce tin de activitatea de administrare de personal?

Confirm cele scrise mai sus. Baza este unica indiferent de sursa modificarii.


> 
> Multumesc,

**Comment by andreea-moisa** [comment]
Buna ziua,
Va multumesc pentru raspuns.Succes! 
Andreea Moisa


Sent from Yahoo Mail for iPhone


On Wednesday, August 21, 2024, 8:37 AM, bogdannedelcu ***@***.***> wrote:





Buna ziua,

Ati putea sa imi spuneti care va fi modul de functionare al Noului Revisal?
   
   - bazele locale actuale de revisal se vor migra in Noul revisal?


Sa va migra baza centrala, veti regasi in noua aplicatie Angajator disponibila online datele incarcate pana la momentul trecerii la noul sistem.

   
   - vor mai exista instalari/baze de date locale de revisal?


Nu vor mai exista baze locale pentru cei care folosesc aplicatia Angajator. Cei care folosesc API probabil vor mentine o baza locala.

   
   - modificarile (nou angajati, Acte Aditionale, Suspendari, Reveniri din Suspendare, Incetari) indiferent daca vin prin import dintr-o aplicatie de HR sau vor fi operate manual se vor scrie intr-o baza de date unica?


Intelegerea este corecta.


In sensul ca daca utilizatorul opteaza pentru operarea manuala sau pentru export xml/rvs dintr-o aplicatie de HR si import in revisal toate aceste modificari se scrie intr-o baza de date unica iar reprezentantul angajatorului are acces la istoricul unui salariat indiferent de sursa unde au fost operate modificarile ce tin de activitatea de administrare de personal?


Confirm cele scrise mai sus. Baza este unica indiferent de sursa modificarii.


Multumesc,
