### ISSUE TITLE
Posibilitate adaugare mai multi salariati sau contracte deodata

### ISSUE THREAD

**Issue by Stihii** [reges-ro/integrare#41]
Se suporta cumva posibilitatea de a adauga mai mult de un salariat sau contract in registru? Am vazut ca se pot face modificari in batch pentru salariat dar nimic legat de inregistrare multipla.

Aceeasi intrebare si pentru modificare in masa a mai multor contracte. Am vazut ca se pot face modificari in masa pe contract, dar doar cu actiune suspendare. Nu avem de exemplu posibilitatea de a modifica salariul in masa pe mai multe contracte.

**Comment by bogdannedelcu** [comment]
Folositi Batch, se pot grupa astfel mai multe adaugari/modificari de salariat sau contract.

**Comment by bogdannedelcu** [comment]
Raspuns si aici https://github.com/reges-ro/integrare/issues/34
