### ISSUE TITLE
CommitRead

### ISSUE THREAD

**Issue by Stihii** [reges-ro/integrare#43]
Nu imi e clar cum functioneaza metoda CommitRead. Dupa ce apelez metoda ReadMessage am inteles ca trebuie sa o folosesc pe cea de CommitRead, dar niciodata nu am primit vreun raspuns cand am apelat-o. Continutul sau este acesta 
`{"messageId" : null}`

**Comment by bogdannedelcu** [comment]
PoolMessage citeste primul mesaj disponibil in coada dvs. si trece la urmatorul. Daca nu exista nici un mesaj in coada nu intoarce nimic.
ReadMessage citeste primul mesaj dar nu trece la urmatorul. Daca apelati de 2 ori la rand ReadMessage veti primi acelasi mesaj. Daca nu exista nici un mesaj in coada nu intoarce nimic.
CommitRead trece la urmatorul mesaj, asta inseamna ca un Read apela dupa Commit este echivalent cu un PoolMessage
