### ISSUE TITLE
Nu se pot adauga salariati

### ISSUE THREAD

**Issue by TestareRev** [reges-ro/integrare#45]
Pe mediul de test(https://reges.test.inspectiamuncii.org/) nu  se pot adauga salariati. 
Desi datele sunt corecte si se trece de validarile specifice din pagina la final se obtine eroarea de mai jos:

Atenție! Informatiile furnizate nu s-au putut transmite. Te rugăm să încerci din nou mai târziu.Id eroare: 682a6005-766d-40a5-bc79-b6816a93033a

**Comment by bogdannedelcu** [comment]
verificam si revenim

**Comment by bogdannedelcu** [comment]
a fost rezolvata problema, puteti sa incercati din nou va rog?
