### ISSUE TITLE
Limit for batch requests

### ISSUE THREAD

**Issue by lalikk** [reges-ro/integrare#48]
Hi, is there a limit how many employees can be registered in a single file or a limit to the size of the file?
Additionally, is there a limit how many submissions I can poll in the PollBatch/ReadBatch/CommitReadBatch requests? 

Thanks

**Comment by cmandragiu** [comment]
Hi Kristína,

The current limit is 100 messages for both batch commands and status check operations (PollBatch/ReadBatch/CommitReadBatch)
