### ISSUE TITLE
Autentificare Cetatean/Angajator

### ISSUE THREAD

**Issue by thomasfrincu** [reges-ro/integrare#5]
Autentificarea prin identidatea digitala (ROeID) va fi disponibila doar pentru zona de "Angajator" sau si pentru "cetatean/salariat"?

**Comment by bogdannedelcu** [comment]
> Autentificarea prin identidatea digitala (ROeID) va fi disponibila doar pentru zona de "Angajator" sau si pentru "cetatean/salariat"?

Ambele zone
