### ISSUE TITLE
Corectii XML

### ISSUE THREAD

**Issue by dototalsoft** [reges-ro/integrare#6]
Buna ziua,

In acest moment corectiile (de salariu, contract, date personale, etc) in aplicatia Revisal se fac direct in baza de date a ITM. 
Prin fisiere XML, se transmit date la un moment dat, care apoi, banuim ca sunt interpretate de soft-ul actual al ITM prin niste reguli de business. 
Daca se opereaza prin fisiere XML, daca initial se transmite un fisier XML cu salariul gresit, cf. instructiunilor din [Răspunsuri la întrebări frecvente privind registrul - revizuit in data de 07.04.2023](https://www.inspectiamuncii.ro/documents/66402/58760675/Raspunsuri+la+situatii+frecvente+privind+registrul+v6.0.9_R.pdf/29505f12-c9a5-432e-a1e9-439fd6451c4b), pentru corectie trebuie transmis ulterior inca un fisier XML cu salariul corect. 
Daca intre timp salariatul respectiv a avut mai multe modificari de contract transmise la ITM, istoricul acelui salariat nu mai poate fi refacut prin fisiere XML. Aveti in vedere si o rezolvare pentru acest tip de probleme? 
De exemplu, asa cum avem tag-urile NumereContractVechi sau CnpVechi, propunem sa se creeze pentru toate tag-urile niste tag-uri corespondente cu <tag+Vechi> astfel incat corectia prin fisiere XML sa poata fi facuta la fel ca si prin aplicatia Revisal. 

Multumesc.

**Comment by bogdannedelcu** [comment]
> Buna ziua,
> 
> 
> 
> In acest moment corectiile (de salariu, contract, date personale, etc) in aplicatia Revisal se fac direct in baza de date a ITM. 
> 
> Prin fisiere XML, se transmit date la un moment dat, care apoi, banuim ca sunt interpretate de soft-ul actual al ITM prin niste reguli de business. 
> 
> Daca se opereaza prin fisiere XML, daca initial se transmite un fisier XML cu salariul gresit, cf. instructiunilor din [Răspunsuri la întrebări frecvente privind registrul - revizuit in data de 07.04.2023](https://www.inspectiamuncii.ro/documents/66402/58760675/Raspunsuri+la+situatii+frecvente+privind+registrul+v6.0.9_R.pdf/29505f12-c9a5-432e-a1e9-439fd6451c4b), pentru corectie trebuie transmis ulterior inca un fisier XML cu salariul corect. 
> 
> Daca intre timp salariatul respectiv a avut mai multe modificari de contract transmise la ITM, istoricul acelui salariat nu mai poate fi refacut prin fisiere XML. Aveti in vedere si o rezolvare pentru acest tip de probleme? 
> 
> De exemplu, asa cum avem tag-urile NumereContractVechi sau CnpVechi, propunem sa se creeze pentru toate tag-urile niste tag-uri corespondente cu <tag+Vechi> astfel incat corectia prin fisiere XML sa poata fi facuta la fel ca si prin aplicatia Revisal. 
> 
> 
> 
> Multumesc.

Buna ziua, luam in considerare sa implementam o astfel de functionalitate in noua aplicatie angajator si prin API
Multumesc
