### ISSUE TITLE
Funcționalități CRUD (Create, Read, Update, Delete)

### ISSUE THREAD

**Issue by veemex** [reges-ro/integrare#7]
GET: Care sunt planurile pentru includerea operațiunilor GET în API? Aveți în vedere adăugarea funcționalităților pentru a permite vizualizarea resurselor, cum ar fi contractele, salariații sau angajatorii? Având în vedere că sistemul nostru stochează complet toate operațiunile și ținând cont de modul în care reconstituiți bazele de date din RVS-urile transmise, există posibilitatea ca anumite operațiuni să nu fie prezente în REGES-ONLINE. În acest context, se pune problema: există vreo limitare în adăugarea operațiunilor retroactive pentru contracte, salariați sau angajatori?

**Comment by bogdannedelcu** [comment]
Aplicatia RevisalOnline va fi accesibila prin browser web si una din identitatile digitale prezentate in sedinda anterioara (RoeID, Semnatura digitala, cont aprobat la sediul ITM). Doar prin intermediul acestei aplicatii se vor putea extrage date din registru, avand trasabilitate completa pana la persoana care solicita datele respective. 

Autentificarea in interfata API se va face cu un token obtinut din aplicatia RevisalOnline, din contul unui utilizator care are drepturi sa acceseze registrul respectiv, token care va fi legat doar de acel registru, pe perioada cat utilizatorul are dreptul legal de a accesa registrul.

Prin interfata API se vor putea transmite date catre REGESOnline si se vor putea receptiona raspunsuri (recipise) la datele trimise. Nu anticipam la acest moment functionalitatea de a extrage date din registru (adica date din istoricul contractelor unui cetatean), motivul fiind ca accesul prin API nu poate garanta o trasabilitate pana la cetateanul care acceseaza datele.

Daca sunt nevoi punctuale pentru a extrage date prin interfata API va rugam sa ne comunicati.

**Comment by veemex** [comment]
> Referitor la actiuni retroactive va rog sa mentionati cateva exemple pentru a intelege mai bine nevoia.


În ceea ce privește exemplele concrete, dacă se efectuează două operațiuni asupra unui element contractual și ulterior transmitem RVS, sistemul REGES va primi doar ultima stare a contractului, ceea ce va duce la pierderea unei operațiuni. Deși acest caz este rar, el poate apărea în bazele de date. De exemplu, dacă majorăm salariul la 5000 lei începând cu data de 1 a lunii și ulterior îl majorăm la 6500 lei începând cu data de 15, iar apoi generăm și transmitem RVS, REGES va înregistra doar ultima modificare. Noi datorita faptului ca am importat din Revisal.db tot istoricul, vom avea intrari in plus fata de ceea ce a primit REGES.

**Comment by veemex** [comment]
> Aplicatia RevisalOnline va fi accesibila prin browser web si una din identitatile digitale prezentate in sedinda anterioara (RoeID, Semnatura digitala, cont aprobat la sediul ITM). Doar prin intermediul acestei aplicatii se vor putea extrage date din registru, avand trasabilitate completa pana la persoana care solicita datele respective.
> 
> Autentificarea in interfata API se va face cu un token obtinut din aplicatia RevisalOnline, din contul unui utilizator care are drepturi sa acceseze registrul respectiv, token care va fi legat doar de acel registru, pe perioada cat utilizatorul are dreptul legal de a accesa registrul.
> 
> Prin interfata API se vor putea transmite date catre REGESOnline si se vor putea receptiona raspunsuri (recipise) la datele trimise. Nu anticipam la acest moment functionalitatea de a extrage date din registru (adica date din istoricul contractelor unui cetatean), motivul fiind ca accesul prin API nu poate garanta o trasabilitate pana la cetateanul care acceseaza datele.
> 
> Daca sunt nevoi punctuale pentru a extrage date prin interfata API va rugam sa ne comunicati.

@bogdannedelcu, ca dezvoltatori de SAAS, considerăm esențial să avem acces complet la lista contractelor și operațiunilor, astfel încât să putem construi o structură personalizată care să funcționeze ca un registru robust pentru clienții noștri.

Citez: „Dezvoltatorii de programe vor avea opțiunea de a exporta lista contractelor cu ID-uri specifice REGES Online, astfel încât să poată asocia aceste ID-uri în software-urile lor pentru a transmite modificări ulterioare asupra documentelor (în scopul completării ReferințeiSalariat și ReferințeiContract).”

Limitarea exportului doar la lista contractelor ar crea o problemă semnificativă, deoarece ar împiedica dezvoltatorii de software să construiască soluții complete și eficiente. În plus, dacă un client dorește să-și înregistreze firma în platforma noastră, ar trebui să refacă manual întregul istoric al contractelor, ceea ce este ineficient și descurajator.

Este crucial ca soluția să nu limiteze utilizatorii în ceea ce privește software-ul pe care îl folosesc și să nu condiționeze accesul la datele necesare. Există un API disponibil, ce permite adaugarea/modificare, însă pentru a susține dezvoltatorii și a îmbunătăți experiența utilizatorului final, accesul la operațiunile de citire a istoricului contractelor/salariaților/angajatorilor este necesar. Acest acces poate fi securizat și monitorizat prin utilizarea certificatelor digitale, care asigură identitatea utilizatorului și oferă un nivel suplimentar de securitate.

Dacă acest acces nu este posibil prin API, ar fi de dorit să se permită cel puțin exportul din RevisalOnline direct din browser a intregului registru ce contine istoric angajator/salariat/contract. În prezent, avem acces nerestricționat la întreaga bază de date prin Revisal.db, și ar fi ideal ca această flexibilitate să fie menținută și în viitor.

**Comment by bogdannedelcu** [comment]
> > Referitor la actiuni retroactive va rog sa mentionati cateva exemple pentru a intelege mai bine nevoia.
> 
> În ceea ce privește exemplele concrete, dacă se efectuează două operațiuni asupra unui element contractual și ulterior transmitem RVS, sistemul REGES va primi doar ultima stare a contractului, ceea ce va duce la pierderea unei operațiuni. Deși acest caz este rar, el poate apărea în bazele de date. De exemplu, dacă majorăm salariul la 5000 lei începând cu data de 1 a lunii și ulterior îl majorăm la 6500 lei începând cu data de 15, iar apoi generăm și transmitem RVS, REGES va înregistra doar ultima modificare. Noi datorita faptului ca am importat din Revisal.db tot istoricul, vom avea intrari in plus fata de ceea ce a primit REGES.

Am notat solicitarea, analizam si revenim cu o propunere

**Comment by bogdannedelcu** [comment]
> > Aplicatia RevisalOnline va fi accesibila prin browser web si una din identitatile digitale prezentate in sedinda anterioara (RoeID, Semnatura digitala, cont aprobat la sediul ITM). Doar prin intermediul acestei aplicatii se vor putea extrage date din registru, avand trasabilitate completa pana la persoana care solicita datele respective.
> > Autentificarea in interfata API se va face cu un token obtinut din aplicatia RevisalOnline, din contul unui utilizator care are drepturi sa acceseze registrul respectiv, token care va fi legat doar de acel registru, pe perioada cat utilizatorul are dreptul legal de a accesa registrul.
> > Prin interfata API se vor putea transmite date catre REGESOnline si se vor putea receptiona raspunsuri (recipise) la datele trimise. Nu anticipam la acest moment functionalitatea de a extrage date din registru (adica date din istoricul contractelor unui cetatean), motivul fiind ca accesul prin API nu poate garanta o trasabilitate pana la cetateanul care acceseaza datele.
> > Daca sunt nevoi punctuale pentru a extrage date prin interfata API va rugam sa ne comunicati.
> 
> @bogdannedelcu, ca dezvoltatori de SAAS, considerăm esențial să avem acces complet la lista contractelor și operațiunilor, astfel încât să putem construi o structură personalizată care să funcționeze ca un registru robust pentru clienții noștri.
> 
> Citez: „Dezvoltatorii de programe vor avea opțiunea de a exporta lista contractelor cu ID-uri specifice REGES Online, astfel încât să poată asocia aceste ID-uri în software-urile lor pentru a transmite modificări ulterioare asupra documentelor (în scopul completării ReferințeiSalariat și ReferințeiContract).”
> 
> Limitarea exportului doar la lista contractelor ar crea o problemă semnificativă, deoarece ar împiedica dezvoltatorii de software să construiască soluții complete și eficiente. În plus, dacă un client dorește să-și înregistreze firma în platforma noastră, ar trebui să refacă manual întregul istoric al contractelor, ceea ce este ineficient și descurajator.
> 
> Este crucial ca soluția să nu limiteze utilizatorii în ceea ce privește software-ul pe care îl folosesc și să nu condiționeze accesul la datele necesare. Există un API disponibil, ce permite adaugarea/modificare, însă pentru a susține dezvoltatorii și a îmbunătăți experiența utilizatorului final, accesul la operațiunile de citire a istoricului contractelor/salariaților/angajatorilor este necesar. Acest acces poate fi securizat și monitorizat prin utilizarea certificatelor digitale, care asigură identitatea utilizatorului și oferă un nivel suplimentar de securitate.
> 
> Dacă acest acces nu este posibil prin API, ar fi de dorit să se permită cel puțin exportul din RevisalOnline direct din browser a intregului registru ce contine istoric angajator/salariat/contract. În prezent, avem acces nerestricționat la întreaga bază de date prin Revisal.db, și ar fi ideal ca această flexibilitate să fie menținută și în viitor.

Am inteles solicitarea cu privire la posibilitatea exportului intregului istoric in vederea initializarii bazelor de date pe programe proprii, Analizam si revenim cu un raspuns.
