### ISSUE TITLE
Eroare adaugare contract-pare a fi de la perioada determinata care depaseste 36 luni

### ISSUE THREAD

**Issue by TestareRev** [reges-ro/integrare#78]
-am adaugat un salariat 
-am adaugat un contract nou cu datele de mai jos

![image](https://github.com/user-attachments/assets/e23a732d-f4a3-43e3-94a5-c98ac4b6a743)
Am obtinut eroare la transmitere contract
Reges OnlineAtenție! Operațiunea nu a putut fi efectuată. Te rugăm să încerci din nou mai târziu.Id eroare: 876362de-469f-41a7-817b-385a953c956f
Banuiesc ca este de la faptul ca am pus o perioada mai mare de 36 luni la contract pe perioada determinata dar nu sunt sigura; daca asta este problema ar fi utila o validare in pagina , sa nu te lase sa salvezi date incorecte , ca altfel nu prea stii care este problema daca primesti un mesaj de eroare de genul Operațiunea nu a putut fi efectuată fara alte detalii despre eroare.

**Comment by bogdannedelcu** [comment]
doar sa ne trimiteti o poza in care sa se vada si cui si userul dvs.

E posibil sa fi fost o problema de moment. Va rog folositi ultima versiune de aplicatie accesand coltul dreapta sus din portal
![Uploading image.png…]()
