### ISSUE TITLE
Operatia de Radiere

### ISSUE THREAD

**Issue by veemex** [reges-ro/integrare#8]
Dorim să solicităm o poziție oficială din partea dvs. cu privire la modul în care radierile salariaților și contractelor ar trebui gestionate de către instituțiile publice și sistemele terțe care folosesc datele din REGES.

Context:
Am întâmpinat o situație în care, deși un salariat și contractul său au fost radiați corect în platforma noastră (câmpul RADIAT=TRUE) si trimis in actualul ".rvs", angajatorul a primit în continuare notificări din partea unei instituții publice, iar contractul respectiv apărea cu starea, activ radiat. Conform înțelegerii noastre, odată ce un salariat sau contract este marcat ca "radiat", acesta ar trebui să fie complet ignorat, fără a mai produce efecte legale sau administrative pentru angajator.

Solicitare:
Având în vedere situația descrisă, dorim să obținem o poziție oficială din partea dvs. care să precizeze în mod clar următoarele:

Confirmarea oficială că odată ce un salariat sau contract este marcat ca radiat (RADIAT=TRUE), acesta nu mai trebuie să producă niciun efect legal sau administrativ pentru angajator, indiferent de starea în care se afla contractul anterior (ex. activ, suspendat etc.).

Clarificări suplimentare în cazurile în care instituțiile publice ignoră sau nu aplică în mod corect această ștergere logică. Cum ar trebui tratate aceste discrepanțe și ce soluții propuneți pentru a asigura o implementare unitară a logicii radierii?

Această clarificare este importantă pentru a evita situații similare în viitor și pentru a ne asigura că utilizatorii nu mai sunt afectați de contracte radiate care, conform definiției, nu ar trebui să producă efecte.

Mulțumim anticipat pentru suport și așteptăm răspunsul dvs. oficial.

**Comment by bogdannedelcu** [comment]
Buna ziua,

Referitor la efectele legale sau administrative mentionez ca depaseste aria de competente asumata de echipa tehica. Va recomand sa va adresati in scris catre Inspectia Muncii o solicitare pentru a clarifica acest caz, includeti datele de identificare ale salariatului, contractului si angajatorului.

Referitor la situatia prezentata putem spune ca un contract marcat ca radiat prin noul API se va salva in baza de date alaturi de metadatele transmise si se va regasi in acea stare la orice alta interogare ulterioara. In noua aplicatia Reges-Online persoanele autorizate vor putea vizualiza aceste informatii si confirma faptul ca ce s-a transmis prin API este corect inregistrat in baza de date.

Multumim
