### ISSUE TITLE
API -> Header.User, Header.Version

### ISSUE THREAD

**Issue by soimbogdan** [reges-ro/integrare#89]
Buna ziua,

Va rog sa-mi clarificati ce [Nume si prenume] utilizator trecem pe Header.User:
1- Utilizatorul care a adaugat inregistrarea in soft
2- Utilizatorul care face POST la modificare in API.

Multumesc,

**Comment by soimbogdan** [comment]
Care este versiunea care o transmitem pe Header.Version ?
Cum urmarim schimbarea ei ?

**Comment by bogdannedelcu** [comment]
Header.Version pentru moment este rezervat pentru o folosire ulterioara. Folositi 0
Header.User este numele utilizatorului care opereaza in softul dvs., este folosit pentru a putea jurnaliza autorul modificarilor.
