### ISSUE TITLE
Eroare adaugare contracte

### ISSUE THREAD

**Issue by TestareRev** [reges-ro/integrare#94]
Am incercat sa adaug de mai multe ori un contract pentru doi angajati si  am obtinut eroare de fiecare data la transmitere contract .

**Reges OnlineAtenție! Operațiunea nu a putut fi efectuată. Te rugăm să încerci din nou mai târziu.Id eroare: 4fbd9105-e8be-4cc3-bac4-0e0088c4ff6c
Reges OnlineAtenție! Operațiunea nu a putut fi efectuată. Te rugăm să încerci din nou mai târziu.Id eroare: 5dd0df91-d484-414d-bf69-636be4022d4821.11.2024, 15:43
Reges OnlineAtenție! Operațiunea nu a putut fi efectuată. Te rugăm să încerci din nou mai târziu.Id eroare: 37c7fb52-7dec-49c3-b1be-895f44c00b5b21.11.2024, 15:47**

La ultimul am salvat datele inante de  a da Transmite
Vedeti mai jos datele , nu  inteleg care este problema deoarece datele sunt corecte din punctul meu de vedere

![image](https://github.com/user-attachments/assets/cbe3b8c0-a609-4ece-b59d-412e60a26d1b)

**Comment by bogdannedelcu** [comment]
nu vedem CUI angajator, se poate un printscreen de browser mare sa vedem si cui si userul dvs?

**Comment by TestareRev** [comment]
![image](https://github.com/user-attachments/assets/2b545341-3898-424f-86f7-0ac7a494b5c7)

**Comment by TestareRev** [comment]
-
