### ISSUE TITLE
Eroare modificare contract

### ISSUE THREAD

**Issue by TestareRev** [reges-ro/integrare#96]
-am mers pe un contract existent si am modificat doar functia COR si am adaugat un spor

![image](https://github.com/user-attachments/assets/b2a2a6f0-824c-49e3-85f8-9a39e20df823)
am obtinut eroare de doua ori
![image](https://github.com/user-attachments/assets/0eaa668c-7361-404b-b044-3e940689ecea)

**Comment by TestareRev** [comment]
[INFO] Log: Action minified:MW INI
main.dart.js:64472 
        
        
        POST https://fapi.dev.inspectiamuncii.org/api/Contract 400 (Bad Request)
(anonymous) @ main.dart.js:64472
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
$1 @ main.dart.js:52029
bi6 @ main.dart.js:5791
(anonymous) @ main.dart.js:137063
uj @ main.dart.js:53243
$0 @ main.dart.js:52479
I5 @ main.dart.js:5663
nZ @ main.dart.js:52401
$0 @ main.dart.js:52449
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bUL @ main.dart.js:5695
bVg @ main.dart.js:5697
$1 @ main.dart.js:51975
childList
$1 @ main.dart.js:51982
bA9 @ main.dart.js:5702
bi7 @ main.dart.js:5809
mD @ main.dart.js:53259
Y1 @ main.dart.js:52408
jz @ main.dart.js:52406
cq @ main.dart.js:52017
n @ main.dart.js:5495
(anonymous) @ main.dart.js:64284
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aVW @ main.dart.js:64285
UA @ main.dart.js:64278
(anonymous) @ main.dart.js:63868
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aGK @ main.dart.js:63887
Gi @ main.dart.js:63843
(anonymous) @ main.dart.js:63759
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
ar2 @ main.dart.js:63838
vg @ main.dart.js:63753
(anonymous) @ main.dart.js:63960
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aex @ main.dart.js:63986
$2 @ main.dart.js:63954
(anonymous) @ main.dart.js:63901
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
$0 @ main.dart.js:63906
$0 @ main.dart.js:52250
bi4 @ main.dart.js:5785
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
$0 @ main.dart.js:53282
$0 @ main.dart.js:52006
setTimeout
amE @ main.dart.js:51991
bSA @ main.dart.js:5485
bo6 @ main.dart.js:5481
bV4 @ main.dart.js:5810
Rf @ main.dart.js:53261
cG @ main.dart.js:5775
yH @ main.dart.js:5549
$1 @ main.dart.js:63895
bi6 @ main.dart.js:5791
(anonymous) @ main.dart.js:137063
uj @ main.dart.js:53243
$0 @ main.dart.js:52479
I5 @ main.dart.js:5663
nZ @ main.dart.js:52401
$0 @ main.dart.js:52449
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bUL @ main.dart.js:5695
bVg @ main.dart.js:5697
$1 @ main.dart.js:51975
childList
$1 @ main.dart.js:51982
bA9 @ main.dart.js:5702
bi7 @ main.dart.js:5809
mD @ main.dart.js:53259
Y1 @ main.dart.js:52408
jz @ main.dart.js:52406
cq @ main.dart.js:52017
n @ main.dart.js:5495
(anonymous) @ main.dart.js:113045
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aVQ @ main.dart.js:113046
guq @ main.dart.js:113035
(anonymous) @ main.dart.js:113094
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aSV @ main.dart.js:113102
qA @ main.dart.js:113090
(anonymous) @ main.dart.js:4247
Nt @ main.dart.js:64041
avS @ main.dart.js:64031
(anonymous) @ main.dart.js:4247
(anonymous) @ main.dart.js:63901
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
$0 @ main.dart.js:63906
$0 @ main.dart.js:52250
bi4 @ main.dart.js:5785
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
$0 @ main.dart.js:53282
$0 @ main.dart.js:52006
setTimeout
amE @ main.dart.js:51991
bSA @ main.dart.js:5485
bo6 @ main.dart.js:5481
bV4 @ main.dart.js:5810
Rf @ main.dart.js:53261
cG @ main.dart.js:5775
yH @ main.dart.js:5549
$1 @ main.dart.js:63895
bi6 @ main.dart.js:5791
(anonymous) @ main.dart.js:137063
uj @ main.dart.js:53243
$0 @ main.dart.js:52479
I5 @ main.dart.js:5663
nZ @ main.dart.js:52401
$0 @ main.dart.js:52449
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bUL @ main.dart.js:5695
bVg @ main.dart.js:5697
$1 @ main.dart.js:51975
childList
$1 @ main.dart.js:51982
bA9 @ main.dart.js:5702
bi7 @ main.dart.js:5809
mD @ main.dart.js:53259
Y1 @ main.dart.js:52408
jz @ main.dart.js:52406
cq @ main.dart.js:52321
nq @ main.dart.js:64000
qA @ main.dart.js:64162
(anonymous) @ main.dart.js:4247
(anonymous) @ main.dart.js:63901
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
$0 @ main.dart.js:63906
$0 @ main.dart.js:52250
bi4 @ main.dart.js:5785
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
$0 @ main.dart.js:53282
$0 @ main.dart.js:52006
setTimeout
amE @ main.dart.js:51991
bSA @ main.dart.js:5485
bo6 @ main.dart.js:5481
bV4 @ main.dart.js:5810
Rf @ main.dart.js:53261
cG @ main.dart.js:5775
yH @ main.dart.js:5549
$1 @ main.dart.js:63895
bi6 @ main.dart.js:5791
(anonymous) @ main.dart.js:137063
uj @ main.dart.js:53243
$0 @ main.dart.js:52479
I5 @ main.dart.js:5663
lP @ main.dart.js:52397
$0 @ main.dart.js:52253
bi4 @ main.dart.js:5785
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
$0 @ main.dart.js:53282
$0 @ main.dart.js:52006
setTimeout
amE @ main.dart.js:51991
bSA @ main.dart.js:5485
bo6 @ main.dart.js:5481
bV4 @ main.dart.js:5810
Rf @ main.dart.js:53261
cG @ main.dart.js:5775
yH @ main.dart.js:5549
(anonymous) @ main.dart.js:63715
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aOj @ main.dart.js:63752
HN @ main.dart.js:63701
(anonymous) @ main.dart.js:63696
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aVa @ main.dart.js:63700
xG @ main.dart.js:63628
aV9 @ main.dart.js:63629
ad9 @ main.dart.js:63626
(anonymous) @ main.dart.js:121334
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aU4 @ main.dart.js:121352
ly @ main.dart.js:121320
(anonymous) @ main.dart.js:40151
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
av4 @ main.dart.js:40157
(anonymous) @ main.dart.js:121871
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
$0 @ main.dart.js:121875
(anonymous) @ main.dart.js:40509
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
bZR @ main.dart.js:40545
kk @ main.dart.js:40504
(anonymous) @ main.dart.js:121857
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
ab @ main.dart.js:121862
(anonymous) @ main.dart.js:4256
XZ @ main.dart.js:61879
(anonymous) @ main.dart.js:61828
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
o @ main.dart.js:5491
aCt @ main.dart.js:61863
zQ @ main.dart.js:61811
aCs @ main.dart.js:61791
b8 @ main.dart.js:61782
(anonymous) @ main.dart.js:122253
(anonymous) @ main.dart.js:5505
$2 @ main.dart.js:52035
$1 @ main.dart.js:52029
bi6 @ main.dart.js:5791
(anonymous) @ main.dart.js:137063
uj @ main.dart.js:53243
$0 @ main.dart.js:52479
I5 @ main.dart.js:5663
nZ @ main.dart.js:52401
$0 @ main.dart.js:52449
bi4 @ main.dart.js:5788
(anonymous) @ main.dart.js:137061
qO @ main.dart.js:53241
ui @ main.dart.js:53216
$0 @ main.dart.js:53293
bUL @ main.dart.js:5695
bVg @ main.dart.js:5697
$1 @ main.dart.js:51975
childList
$1 @ main.dart.js:51982
bA9 @ main.dart.js:5702
bi7 @ main.dart.js:5809
mD @ main.dart.js:53259
Y1 @ main.dart.js:52408
jz @ main.dart.js:52406
cq @ main.dart.js:52321
fz @ main.dart.js:52322
a5h @ main.dart.js:90213
bo3 @ main.dart.js:22325
mK @ main.dart.js:66371
XS @ main.dart.js:66374
nf @ main.dart.js:66339
cr @ main.dart.js:66340
B1 @ main.dart.js:72920
aaf @ main.dart.js:73315
(anonymous) @ main.dart.js:4245
aaX @ main.dart.js:69599
dn @ main.dart.js:69604
aah @ main.dart.js:70028
YI @ main.dart.js:70000
iF @ main.dart.js:69982
Xn @ main.dart.js:68518
me @ main.dart.js:68600
aNm @ main.dart.js:68592
a0Y @ main.dart.js:68586
SC @ main.dart.js:68577
MZ @ main.dart.js:68575
avw @ main.dart.js:68563
(anonymous) @ main.dart.js:4246
bi6 @ main.dart.js:5794
(anonymous) @ main.dart.js:137063
uj @ main.dart.js:53243
oU @ main.dart.js:53220
u1 @ main.dart.js:1263
aST @ main.dart.js:45429
(anonymous) @ main.dart.js:4247
v9 @ main.dart.js:45481
$1 @ main.dart.js:45734
$1 @ main.dart.js:45687
$1 @ main.dart.js:45484
bTe @ main.dart.js:8357
(anonymous) @ main.dart.js:8348
main.dart.js:39252 [2024-11-22 11:37:41.604 | Log | INFO] Action minified:JM INI
main.dart.js:39252 [INFO] Log: Action minified:JM INI
main.dart.js:39252 [2024-11-22 11:37:41.605 | Log | INFO] Action minified:B9 INI
main.dart.js:39252 [INFO] Log: Action minified:B9 INI
main.dart.js:39252 [2024-11-22 11:37:41.614 | Log | INFO] Action minified:B9 END
main.dart.js:39252 [INFO] Log: Action minified:B9 END
main.dart.js:39252 [2024-11-22 11:37:41.616 | Log | INFO] Action minified:JM END
main.dart.js:39252 [INFO] Log: Action minified:JM END
main.dart.js:39252 [2024-11-22 11:37:41.619 | Log | INFO] Action minified:MW END
main.dart.js:39252 [INFO] Log: Action minified:MW END
main.dart.js:39252 [2024-11-22 11:37:41.621 | Log | INFO] Action minified:pv.pop() INI
main.dart.js:39252 [INFO] Log: Action minified:pv.pop() INI
main.dart.js:39252 [2024-11-22 11:37:41.623 | Log | INFO] Action minified:pv.pop() END
main.dart.js:39252 [INFO] Log: Action minified:pv.pop() END
main.dart.js:39252 [2024-11-22 11:37:41.625 | Log | INFO] Action minified:nS INI
main.dart.js:39252 [INFO] Log: Action minified:nS INI
main.dart.js:39252 [2024-11-22 11:37:41.627 | Log | INFO] Action minified:Aw INI
main.dart.js:39252 [INFO] Log: Action minified:Aw INI
main.dart.js:39252 [2024-11-22 11:37:41.629 | Log | INFO] Action minified:Aw END
main.dart.js:39252 [INFO] Log: Action minified:Aw END
main.dart.js:39252 [2024-11-22 11:37:41.630 | Log | INFO] Action minified:vW INI
main.dart.js:39252 [INFO] Log: Action minified:vW INI
main.dart.js:39252 [2024-11-22 11:37:41.632 | Log | INFO] Action minified:vW END
main.dart.js:39252 [INFO] Log: Action minified:vW END
main.dart.js:39252 [2024-11-22 11:37:41.635 | Log | INFO] Action minified:nS END
main.dart.js:39252 [INFO] Log: Action minified:nS END
main.dart.js:39252 [2024-11-22 11:37:41.783 | Catcher 2 | INFO] ============================== CATCHER 2 LOG ==============================
main.dart.js:39252 [2024-11-22 11:37:41.784 | Catcher 2 | INFO] Crash occurred on 2024-11-22 11:37:41.782
main.dart.js:39252 [2024-11-22 11:37:41.785 | Catcher 2 | INFO] 
main.dart.js:39252 [2024-11-22 11:37:41.785 | Catcher 2 | INFO] ------- DEVICE INFO -------
main.dart.js:39252 [2024-11-22 11:37:41.785 | Catcher 2 | INFO] language: en-US
main.dart.js:39252 [2024-11-22 11:37:41.786 | Catcher 2 | INFO] appCodeName: Mozilla
main.dart.js:39252 [2024-11-22 11:37:41.786 | Catcher 2 | INFO] appName: Netscape
main.dart.js:39252 [2024-11-22 11:37:41.787 | Catcher 2 | INFO] appVersion: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
main.dart.js:39252 [2024-11-22 11:37:41.787 | Catcher 2 | INFO] browserName: BrowserName.edge
main.dart.js:39252 [2024-11-22 11:37:41.788 | Catcher 2 | INFO] deviceMemory: 8
main.dart.js:39252 [2024-11-22 11:37:41.788 | Catcher 2 | INFO] hardwareConcurrency: 8
main.dart.js:39252 [2024-11-22 11:37:41.788 | Catcher 2 | INFO] languages: [en-US, en, ro]
main.dart.js:39252 [2024-11-22 11:37:41.788 | Catcher 2 | INFO] maxTouchPoints: 0
main.dart.js:39252 [2024-11-22 11:37:41.789 | Catcher 2 | INFO] platform: Win32
main.dart.js:39252 [2024-11-22 11:37:41.789 | Catcher 2 | INFO] product: Gecko
main.dart.js:39252 [2024-11-22 11:37:41.789 | Catcher 2 | INFO] productSub: 20030107
main.dart.js:39252 [2024-11-22 11:37:41.789 | Catcher 2 | INFO] userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
main.dart.js:39252 [2024-11-22 11:37:41.790 | Catcher 2 | INFO] vendor: Google Inc.
main.dart.js:39252 [2024-11-22 11:37:41.790 | Catcher 2 | INFO] vendorSub: 
main.dart.js:39252 [2024-11-22 11:37:41.790 | Catcher 2 | INFO] 
main.dart.js:39252 [2024-11-22 11:37:41.790 | Catcher 2 | INFO] ------- APP INFO -------
main.dart.js:39252 [2024-11-22 11:37:41.791 | Catcher 2 | INFO] environment: release
main.dart.js:39252 [2024-11-22 11:37:41.791 | Catcher 2 | INFO] version: 1.0.0
main.dart.js:39252 [2024-11-22 11:37:41.791 | Catcher 2 | INFO] appName: revisal_web
main.dart.js:39252 [2024-11-22 11:37:41.791 | Catcher 2 | INFO] buildNumber: 1
main.dart.js:39252 [2024-11-22 11:37:41.792 | Catcher 2 | INFO] packageName: revisal_web
main.dart.js:39252 [2024-11-22 11:37:41.792 | Catcher 2 | INFO] 
main.dart.js:39252 [2024-11-22 11:37:41.792 | Catcher 2 | INFO] ---------- ERROR ----------
main.dart.js:39252 [2024-11-22 11:37:41.793 | Catcher 2 | INFO] Exception: DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.


 **Error id:** 0f862518-18dd-4e95-a2e2-07b6c30952dc
main.dart.js:39252 [2024-11-22 11:37:41.793 | Catcher 2 | INFO] 
main.dart.js:39252 [2024-11-22 11:37:41.794 | Catcher 2 | INFO] ------- STACK TRACE -------
main.dart.js:39252 [2024-11-22 11:37:41.794 | Catcher 2 | INFO] 
main.dart.js:39252 [2024-11-22 11:37:41.794 | Catcher 2 | INFO]     at Object.c (https://reges.test.inspectiamuncii.org/app/main.dart.js:4110:19)
main.dart.js:39252 [2024-11-22 11:37:41.795 | Catcher 2 | INFO]     at https://reges.test.inspectiamuncii.org/app/main.dart.js:63745:9
main.dart.js:39252 [2024-11-22 11:37:41.795 | Catcher 2 | INFO]     at bin.a (https://reges.test.inspectiamuncii.org/app/main.dart.js:5505:63)
main.dart.js:39252 [2024-11-22 11:37:41.795 | Catcher 2 | INFO]     at bin.$2 (https://reges.test.inspectiamuncii.org/app/main.dart.js:52035:14)
main.dart.js:39252 [2024-11-22 11:37:41.795 | Catcher 2 | INFO]     at bgU.$2 (https://reges.test.inspectiamuncii.org/app/main.dart.js:52032:16)
main.dart.js:39252 [2024-11-22 11:37:41.795 | Catcher 2 | INFO]     at Object.bi5 (https://reges.test.inspectiamuncii.org/app/main.dart.js:5797:19)
main.dart.js:39252 [2024-11-22 11:37:41.796 | Catcher 2 | INFO]     at a9m.<anonymous> (https://reges.test.inspectiamuncii.org/app/main.dart.js:137065:10)
main.dart.js:39252 [2024-11-22 11:37:41.796 | Catcher 2 | INFO]     at ae7.xL (https://reges.test.inspectiamuncii.org/app/main.dart.js:53245:12)
main.dart.js:39252 [2024-11-22 11:37:41.796 | Catcher 2 | INFO]     at nk.aP5 (https://reges.test.inspectiamuncii.org/app/main.dart.js:52328:18)
main.dart.js:39252 [2024-11-22 11:37:41.796 | Catcher 2 | INFO]     at b50.$0 (https://reges.test.inspectiamuncii.org/app/main.dart.js:52489:37)
main.dart.js:39252 [2024-11-22 11:37:41.797 | Catcher 2 | INFO] ======================================================================
main.dart.js:39252 [2024-11-22 11:37:41.798 | Catcher 2 | INFO] minified:a1q successfully reported an error
main.dart.js:39252 [2024-11-22 11:37:41.798 | Catcher 2 | INFO] Sending request to Discord server...
main.dart.js:39252 [2024-11-22 11:37:42.237 | Catcher 2 | INFO] Server responded with code: 204 and message: 
main.dart.js:39252 [2024-11-22 11:37:42.237 | Catcher 2 | INFO] minified:a2m successfully reported an error

**Comment by TestareRev** [comment]
Acolo nu apare nimica

**Comment by bogdannedelcu** [comment]
trebuie sa apara ceva la Payload, ca altfel nu da acel 400
POST https://fapi.dev.inspectiamuncii.org/api/Contract 400 (Bad Request)

**Comment by bogdannedelcu** [comment]
sigur folositi versiunea 1044? 
https://reges.test.inspectiamuncii.org/app/v1044/index.html#main

**Comment by TestareRev** [comment]
Nu aveam versiunea 1044 intr-adevar. intram pe un link salvat .

**Comment by TestareRev** [comment]
-

**Comment by bogdannedelcu** [comment]
bun, sa folositi va rog link-ul din coltul dreapta sus pentru ca se vor mai schimba versiunile

![image](https://github.com/user-attachments/assets/c34aba72-a834-415e-ac4b-ace52b3e9ea3)
