### ISSUE TITLE
Extras contract- lipseste interval orar (la repartizare timp munca=Zilnic)

### ISSUE THREAD

**Issue by TestareRev** [reges-ro/integrare#97]
![image](https://github.com/user-attachments/assets/5beaccc0-4508-4149-b24e-90135f461f96)

![image](https://github.com/user-attachments/assets/1c0d1dc3-6389-4154-a866-1d02fe420024)

**Comment by bogdannedelcu** [comment]
va rog verificati daca este ok acum
